### ISSUE TITLE
Cannot sign in with Chrome OS

### ISSUE THREAD

**Issue by hamperfait** [peterjosling/scroball#59]
I am using a Chromebook to listen to music, using the Android compatibility.
I get to the home screen and press Sign in.
I get redirected to last.fm, I allow access to scroball, but scroball stays in the main page, I can log in as often as I want, but the screen does not change.
Is there a way to solve that?
Thanks

**Comment by peterjosling** [comment]
I've not found a way to fix this on my side yet, and I think it's a bug in the ChromeOS Android integration.

As a workaround you can install Chrome Beta or Canary from Google Play on the Chromebook, then select that as the browser when you go to sign in from Scroball. From there it should redirect back to the app correctly once you've signed in. After that you can delete the additional Chrome app.

**Comment by hamperfait** [comment]
That worked! Thanks a lot!
